#spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    #MySQL配置
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.200.132:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
#    username: root
#    password: 123456
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.200.132:8848
#  application:
#    name: gulimall-ware
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#mybatis-plus:
#  mapper-locations: classpath:mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#server:
#  port: 7400
#logging:
#  level:
#    com.losgai.gulimall: debug